### ISSUE TITLE
Client crash when mining

### ISSUE THREAD

**Issue by laxika** [powerbot/RSBot-API#2081]
Hi guys,

I get a client crash **consistently** while mining clay/tin/copper in the Burthrope caves or Varrock,

```
07:50 Startup: RSBot/7112 (Windows NT 10.0; WOW64) Java/1.8.0_181 [#32; 768 MiB]
07:50 Welcome: select your game, then to play a script click File > Play
Error: client.init:1096 sun.reflect.NativeMethodAccessorImpl.invoke0 sun.reflect.NativeMethodAccessorImpl.invoke:62 sun.reflect.DelegatingMethodAccessorImpl.invoke:43 java.lang.reflect.Method.invoke:498 Rs2Applet.a:195 Rs2Applet.init:437 app.appletviewer.lambda$load$0:103 java.awt.event.InvocationEvent.dispatch:311 java.awt.EventQueue.dispatchEventImpl:758 java.awt.EventQueue.access$500:97 java.awt.EventQueue$3.run:709 java.awt.EventQueue$3.run:703 java.security.AccessController.doPrivileged java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege:74 java.awt.EventQueue.dispatchEvent:728 java.awt.EventDispatchThread.pumpOneEventForFilters:205 java.awt.EventDispatchThread.pumpEventsForFilter:116 java.awt.EventDispatchThread.pumpEventsForHierarchy:105 java.awt.EventDispatchThread.pumpEvents:101 java.awt.EventDispatchThread.pumpEvents:93 java.awt.EventDispatchThread.run:82 | java.lang.RuntimeException | 
07:51 Updates: rt6 5eac26438d97c611bc232986ffea7cf5097c280f
apo: java.lang.reflect.InvocationTargetException
	at te.a(te.java:139)
	at te.u(te.java:108)
	at afp.<init>(afp.java:252)
	at cv.u(cv.java:14)
	at dp.c(dp.java:66)
	at amw.u(amw.java:60)
	at gw.fh(gw.java:2069)
	at yj.fs(yj.java:2022)
	at ajk.fa(ajk.java:2015)
	at ey.l(ey.java:609)
	at ajw.s(ajw.java:258)
	at client.ae(client.java:1539)
	at sx.z(sx.java:573)
	at sx.t(sx.java:549)
	at sx.run(sx.java:506)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at te.a(te.java:130)
	... 15 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Laxika\jagexcache\runescape\LIVE\jaclib.dll: A megadott eljárás nem található
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	... 20 more
Error: n.u() ol.q() ahd.ih() c.iz() aam.hm() c.kv() c.kv() agl.kd() c.kv() c.kv() c.kv() c.kv() agl.kd() ce.kf() fe.hs() client.ab() sx.j() sx.t() | afl.cy:1615 n.u:570 ol.q:82 ahd.ih:5965 c.iz:5607 aam.hm:4568 c.kv:10397 c.kv:10481 agl.kd:10323 c.kv:10485 c.kv:10481 c.kv:10481 c.kv:10481 agl.kd:10323 ce.kf:10308 fe.hs:4413 client.ab:1636 sx.j:598 sx.t:550 sx.run:506 java.lang.Thread.run:748 | java.lang.IllegalArgumentException:  |  2208,4456,104,104 0,2261,4504 0 0 2 1008,709 0 0 0 0 0 0 769 12 0 GQECbcil68vh8dn40CdCoIKGel5MFO2X
error_game_crash
```

Is this caused by RSBot or Jagex?

**Comment by Strikegently** [comment]
Delete your jagex cache and re-launch the client to rebuild it. See if that helps.

**Comment by Strikegently** [comment]
@laxika 

Figured something out. You cannot load OpenGL/DirectX libraries while using the JDK. You need to change your RSBot launch configuration to use JRE - **NOT JDK**. 

The game crash while mining in safe mode is still ultimately a Jagex issue - I verified it in the official client - so there's no way for us to fix it.

**Comment by Paris** [comment]
Interesting, I wonder if I should have the bot show a warning message under these circumstances.

@ChrisBeecroft note the above so if anyone posts a support message you can advise them about it.
