### ISSUE TITLE
Class cast exception

### ISSUE THREAD

**Issue by tanlines** [powerbot/RSBot-API#2082]
```
12:30 Script: error loading script
java.lang.ClassCastException: class s.zB
    at java.lang.Class.asSubclass(Unknown Source)
    at org.powerbot.bot.ScriptList.load(ScriptList.java:194)
    at z.COm2.goto(BotPreferences.java:386)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
    at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
    at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
    at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by ChrisBPB** [comment]
Please provide information on how to reproduce the error

**Comment by tanlines** [comment]
Was a user report, last time I posted in discord I was told to make it a github issue. Just ran my MrCrabs script and error came up.

**Comment by benpoulson** [comment]
The only thing I can imagine on this is:

* The API served an incorrect className for some reason.
* The user opened the script list, left it open for a while. An update was was pushed to the script which could change the className. User returns and runs said script, causing the ScriptBundle data to be out of date.

My assumptions here are that the className changes upon bundle rebuild.

**Comment by Paris** [comment]
Does this still happen?

**Comment by tanlines** [comment]
Apparently not.
