### ISSUE TITLE
AbstractScript.getFile throws SecurityException for some

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/RSBot-API#2096]
```
23:11 Startup: RSBot/7114 (Macintosh; Intel Mac OS X 10_11_6) Java/9.0.4 [#2; 1024 MiB]
23:11 Welcome: select your game, then to play a script click File > Play (⌘,)
23:12 Updates: rt4 a61c715395e0faf1ffcbf33fff559ebb715f4f3e
23:13 Script: starting AMiner OS
23:13 Debug: Initialized antipatterns!
23:13 Script: bootstrap
java.lang.SecurityException
    at org.powerbot.cON.checkPermission(Sandbox.java:72)
    at java.base/java.lang.SecurityManager.checkWrite(Unknown Source)
    at java.base/java.io.File.mkdir(Unknown Source)
    at java.base/java.io.File.mkdirs(Unknown Source)
    at java.base/java.io.File.mkdirs(Unknown Source)
    at org.powerbot.script.AbstractScript.getStorageDirectory(AbstractScript.java:168)
    at org.powerbot.script.AbstractScript.getFile(AbstractScript.java:223)
```

**Comment by Paris** [comment]
This no longer appears to happen but please update with a comment if it does.

**Comment by ArtificialPB** [comment]
Still happens:
```

22:12 Startup: RSBot/7120 (Macintosh; Intel Mac OS X 10_11_6) Java/9.0.4 [#2; 768 MiB]
22:13 Welcome: select your game, then to play a script click File > Play (⌘,)
22:13 Updates: rt4 6kelnbyd
22:14 Script: starting AMiner OS
22:14 Debug: Initialized antipatterns!
22:14 Script: bootstrap
java.lang.SecurityException
    at org.powerbot.aUx.checkPermission(Sandbox.java:75)
    at java.base/java.lang.SecurityManager.checkWrite(SecurityManager.java:988)
    at java.base/java.io.File.mkdir(File.java:1323)
    at java.base/java.io.File.mkdirs(File.java:1355)
    at java.base/java.io.File.mkdirs(File.java:1366)
    at org.powerbot.script.AbstractScript.getStorageDirectory(AbstractScript.java:168)
    at org.powerbot.script.AbstractScript.getFile(AbstractScript.java:223)
```

This is the part of the code that fails: `ctx.controller.script().getFile("ScriptProperties.ini");`. I'm unable to replicate. Let me know what more info would help you identify the problem.

**Comment by k0na** [comment]
This recently started happening for me as well @Paris.

```java.lang.SecurityException
	at org.powerbot.con.checkPermission(Sandbox.java:75)
	at java.base/java.lang.SecurityManager.checkWrite(SecurityManager.java:752)
	at java.base/java.io.File.mkdir(File.java:1325)
	at java.base/java.io.File.mkdirs(File.java:1357)
	at java.base/java.io.File.mkdirs(File.java:1368)
	at org.powerbot.script.AbstractScript.getStorageDirectory(AbstractScript.java:165)```

**Comment by Paris** [comment]
Calls from `ImageIO` will not have this exception thrown in the next version.

**Comment by k0na** [comment]
How about `AbstractScript#getStorageDirectory` @Paris?

**Comment by k0na** [comment]
This is still happening for me when calling `AbstractScript#getStorageDirectory` @Paris.

**Comment by Paris** [comment]
After extensive testing with @k0na this appears to be a [bug in Java](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8170900) which can be resolved by creating the folder manually then optionally deleting it. JRE 11 seems to have the issue regardless on some platforms.
