### ISSUE TITLE
BufferUnderflowException - Random Events

### ISSUE THREAD

**Issue by RZME** [powerbot/RSBot-API#2103]
Exception sporadically raised due to this code snippet:
`!ctx.npcs.select().within(5d).action("Dismiss").select(npc
                -> npc.interacting().equals(ctx.players.local())).isEmpty()`

`java.nio.BufferUnderflowException
	at org.powerbot.bot.cache.JagexStream.false(JagexStream.java:74)
	at org.powerbot.bot.cache.JagexStream.getByte(JagexStream.java:60)
	at org.powerbot.bot.cache.JagexStream.getUByte(JagexStream.java:84)
	at org.powerbot.bot.cache.JagexStream.getUShort(JagexStream.java:88)
	at org.powerbot.script.rt4.CacheNpcConfig.read(CacheNpcConfig.java:70)
	at org.powerbot.script.rt4.CacheNpcConfig.<init>(CacheNpcConfig.java:47)
	at org.powerbot.script.rt4.CacheNpcConfig.load(CacheNpcConfig.java:59)
	at org.powerbot.script.rt4.Npc.actions(Npc.java:85)
	at org.powerbot.script.Actionable$Matcher.accept(Actionable.java:78)
	at org.powerbot.script.Actionable$Matcher.accept(Actionable.java:53)
	at org.powerbot.script.AbstractQuery.select(AbstractQuery.java:98)
	at org.powerbot.script.rt4.BasicQuery.action(BasicQuery.java:161)`

**Comment by Strikegently** [comment]
#2101
